### PR TITLE
Pass opts to dnode when creating client.

### PR DESCRIPTION
**Pull request by MiniGod**
For passing options to `dnode`.
For instance to disable weak (`opts.weak = false`).

### CODE REVIEW

**Comment by MiniGod** [comment]
A bit unrelated to this PR, but I had to fix a race-condition in the tests that assumed at least a millisecond delay between `up`s.

**Comment by agirorn** [comment]
Finally, we will be able to run upnode in Electron. All hail the mighty MiniGod.

**Comment by agirorn** [comment]
@substack can we get this merged in or is something blocking this?

**Comment by agirorn** [comment]
@mreinstein thanks for the merge and the new release.

**Pull request merged**
